# Generated by Django 4.2.3 on 2023-07-08 23:48

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("spatial_convertor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatiallayer",
            name="layer",
            field=picklefield.fields.PickledObjectField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
