# Generated by Django 4.2.3 on 2023-07-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial_convertor", "0002_alter_spatiallayer_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatiallayer",
            name="layer",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
